### ISSUE TITLE
Couldn't find nearby device for address

### ISSUE THREAD

**Issue by DerGary** [rikroe/cometblue-custom-component#5]
Hey Richard,

me again 🙈

After working around the error that the thermostats turn unavailable, I now got an error that is similar to that. The device is also listed as unavailable but in the Integration I got the following error messages:

![image](https://github.com/user-attachments/assets/c755ce76-e7f6-4a20-8a48-09e3918f307c)

The only way to resolve that issue for a specific thermostat is to remove the battery of that thermostat. After that It works again. Resetting it in the Menu or trying to reload Home Assistant or the config of the device does not resolve the issue. (After writing this issue, I encountered one thermostat that did recover on it's own but others don't 🤷)

Looking at the logs It seems like the issue happens when this message is logged:

`2024-12-02 06:38:51.547 ERROR (MainThread) [custom_components.eurotronic_cometblue.coordinator] Error fetching Comet Blue D0:B5:C2:FA:D7:98 data: Error retrieving data: No backend with an available connection slot that can reach address D0:B5:C2:FA:D7:98 was found`

I read in [this comment](https://github.com/home-assistant/core/issues/79685#issuecomment-1270857001) of a thread describing a similar issue, that it may have to do with the integration not releasing the connection?

I currently got 6 Bluetooth proxies and 6 Thermostats so there should be enough possible connections 😅

Do you have any idea for that?

**Comment by rikroe** [comment]
Sorry for the delay in answering.

I had a similar thing (and somebody else mentioned something close in discord today). However nothing breaking on my side right now. All is working. 

Have you tried restarting the Bluetooth proxy instead of the thermostat?

I actually added a button to my ESPHome configuration to restart or start scanning. 
However I didn't need to use it lately. 

Do you have a lot of other Bluetooth devices around that could mess with it? 

I use 2 ESPs for 4 TRVs. 

```yaml
substitutions:
  name: badge-01
  encryption_key: ... 

esphome:
  name: ${name}

esp32:
  board: esp32-pro
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: ""

# Enable Home Assistant API
api:
  encryption:
    key: ${encryption_key}
  services:
    - service: start_ble_scan
      then:
        - esp32_ble_tracker.start_scan:

button:
  - platform: restart
    name: "${name} restart"

binary_sensor:
  - platform: status
    name: "${name} status"

bluetooth_proxy:
  active: True
  # cache_services: True

esp32_ble_tracker:
  scan_parameters:
    active: True  # Keep it True for now
```
